/* Curso IA ChatGPT v19.5 — correcciones de estabilización y diagnóstico */
(()=>{
'use strict';
const $=id=>document.getElementById(id);
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const text=(id,msg)=>{const n=$(id);if(n)n.textContent=msg||'';};
const langs=['es','en','fr','de','it','pt'];

function activeWorkspace(){return [...document.querySelectorAll('.workspace.open')].find(x=>getComputedStyle(x).display!=='none')||null;}
function slowScroll(el,to,duration=900){if(!el)return;const from=el.scrollTop,delta=to-from,start=performance.now();const step=now=>{const p=Math.min(1,(now-start)/duration),e=1-Math.pow(1-p,3);el.scrollTop=from+delta*e;if(p<1)requestAnimationFrame(step);};requestAnimationFrame(step);}
function patchScrolling(){
 const down=$('workspaceScrollBottomBtn');
 if(down&&!down.dataset.v195){down.dataset.v195='1';down.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();const w=activeWorkspace();if(w)slowScroll(w,w.scrollHeight,1050);},true);}
 document.addEventListener('click',e=>{const target=e.target.closest('[data-open-zone],[data-admin-tab],.tab,[role="tab"]');if(!target)return;setTimeout(()=>{const w=activeWorkspace();if(w)w.scrollTop=0;window.scrollTo(0,0);},30);},true);
 document.querySelectorAll('select[id$="ChapterSelect"],#chapterSelect').forEach(s=>s.addEventListener('change',()=>setTimeout(()=>{const w=activeWorkspace();if(w)w.scrollTop=0;},20),true));
}

async function getSession(){try{if(typeof session!=='undefined'&&session?.user)return session;const r=await sb.auth.getSession();return r.data?.session||null;}catch{return null;}}
async function copyPlain(v){try{await navigator.clipboard.writeText(v);}catch{const a=document.createElement('textarea');a.value=v;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove();}}

function ensureNoteEditDialog(){if($('v195NoteEditDialog'))return;const d=document.createElement('dialog');d.id='v195NoteEditDialog';d.className='chapter-dialog';d.innerHTML='<div class="dialog-body"><h2>Editar nota</h2><input id="v195NoteId" type="hidden"><label>Título</label><input id="v195NoteTitle" type="text"><label>Tipo</label><select id="v195NoteType"><option value="note">Nota</option><option value="idea">Idea</option><option value="prompt">Prompt</option><option value="test">Prueba</option><option value="application">Aplicación</option><option value="task">Tarea pendiente</option></select><label>Capítulo</label><select id="v195NoteChapter"></select><label>Anotación</label><textarea id="v195NoteBody" rows="8"></textarea><div id="v195NoteMsg" class="muted"></div><div class="btnrow"><button id="v195NoteSave" class="btn primary" type="button">Guardar cambios</button><button id="v195NoteCancel" class="btn" type="button">Cancelar</button></div></div>';document.body.appendChild(d);$('v195NoteChapter').innerHTML='<option value="">Sin capítulo</option>'+Array.from({length:17},(_,i)=>`<option value="${i+1}">Capítulo ${i+1}</option>`).join('');$('v195NoteCancel').onclick=()=>d.close();$('v195NoteSave').onclick=saveEditedNote;}
async function openEditedNote(id){ensureNoteEditDialog();text('v195NoteMsg','Cargando…');const {data,error}=await sb.from('course_notes').select('id,title,note_type,chapter_number,body').eq('id',id).maybeSingle();if(error||!data){text('v195NoteMsg',error?.message||'No se pudo cargar la nota.');return;}$('v195NoteId').value=data.id;$('v195NoteTitle').value=data.title||'';$('v195NoteType').value=data.note_type||'note';$('v195NoteChapter').value=data.chapter_number?String(data.chapter_number):'';$('v195NoteBody').value=data.body||'';text('v195NoteMsg','');$('v195NoteEditDialog').showModal();}
async function saveEditedNote(){const id=$('v195NoteId').value,title=$('v195NoteTitle').value.trim(),body=$('v195NoteBody').value.trim();if(!title||!body){text('v195NoteMsg','Título y anotación son obligatorios.');return;}text('v195NoteMsg','Guardando…');const payload={title,body,note_type:$('v195NoteType').value,chapter_number:$('v195NoteChapter').value?Number($('v195NoteChapter').value):null,updated_at:new Date().toISOString()};const {error}=await sb.from('course_notes').update(payload).eq('id',id);if(error){text('v195NoteMsg',error.message);return;}const card=document.querySelector(`[data-edit="${CSS.escape(id)}"]`)?.closest('.note-item');if(card){const h=card.querySelector('.note-title'),b=card.querySelector('.note-body');if(h)h.textContent=title;if(b)b.textContent=body;}$('v195NoteEditDialog').close();}
async function deleteNote(id){if(!confirm('¿Eliminar esta nota?'))return;const {error}=await sb.from('course_notes').delete().eq('id',id);if(error){alert(error.message);return;}document.querySelector(`[data-del="${CSS.escape(id)}"]`)?.closest('.note-item')?.remove();}
async function copyNote(id){const {data,error}=await sb.from('course_notes').select('body').eq('id',id).maybeSingle();if(error||!data){alert(error?.message||'No se pudo copiar.');return;}await copyPlain(String(data.body||''));text('notesStatus','Copiado únicamente el texto de la anotación.');}
function patchNotes(){ensureNoteEditDialog();document.addEventListener('click',e=>{const edit=e.target.closest('[data-edit]'),del=e.target.closest('[data-del]'),copy=e.target.closest('[data-copy]');if(edit){e.preventDefault();e.stopImmediatePropagation();openEditedNote(edit.dataset.edit);return;}if(del){e.preventDefault();e.stopImmediatePropagation();deleteNote(del.dataset.del);return;}if(copy){e.preventDefault();e.stopImmediatePropagation();copyNote(copy.dataset.copy);}},true);}

async function robustProfileSave(e){
 e.preventDefault();e.stopImmediatePropagation();
 const s=await getSession();if(!s)return;let field='';try{field=profileEditField||'';}catch{}
 const input=$('profileEditInput'),lang=$('profileEditLanguage');text('profileEditMsg','Guardando…');
 try{
   if(field==='name'){
     const value=input.value.trim();const {error}=await sb.rpc('update_my_course_profile',{p_display_name:value,p_preferred_language:(accessProfile?.preferred_language||currentLanguage||'es')});if(error)throw error;await sb.auth.updateUser({data:{...(s.user.user_metadata||{}),display_name:value}});
   }else if(field==='language'){
     const value=lang.value;if(!langs.includes(value))throw new Error('Idioma no válido.');const {error}=await sb.rpc('update_my_course_profile',{p_display_name:accessProfile?.display_name||'',p_preferred_language:value});if(error)throw error;await sb.auth.updateUser({data:{...(s.user.user_metadata||{}),preferred_language:value}});try{currentLanguage=value;pendingLoginLanguage=null;localStorage.setItem('curso_ia_language',value);applyLanguage();}catch{}
   }else if(field==='password'){
     const value=input.value;if(value.length<8)throw new Error('La contraseña debe tener al menos 8 caracteres.');const {error}=await sb.auth.updateUser({password:value});if(error)throw error;
   }else if(field==='email'){
     const value=input.value.trim().toLowerCase();const {error}=await sb.auth.updateUser({email:value});if(error)throw error;text('profileEditMsg','Se ha solicitado el cambio. Revisa el correo de confirmación si Supabase lo requiere.');return;
   }else return;
   if(typeof refreshAccess==='function')await refreshAccess();if(typeof renderProfileCard==='function')renderProfileCard();if(typeof loadCourseContent==='function')await loadCourseContent(false);if(typeof safeRenderAll==='function')safeRenderAll();text('profileEditMsg','Cambios guardados.');setTimeout(()=>$('profileEditDialog')?.close(),350);
 }catch(err){text('profileEditMsg',err?.message||String(err));}
}
function patchProfile(){const b=$('saveProfileFieldBtn');if(b&&!b.dataset.v195){b.dataset.v195='1';b.addEventListener('click',robustProfileSave,true);}}

async function adminCall(body){const {data,error}=await sb.functions.invoke('invite-course-user',{body});if(error||data?.error)throw new Error(data?.error||error?.message||'Operación no completada.');return data;}
async function openAdminEdit(email){const {data,error}=await sb.from('course_users').select('email,display_name,role,active,preferred_language').eq('email',email).maybeSingle();if(error||!data){alert(error?.message||'Usuario no encontrado.');return;}$('editUserEmail').value=data.email;$('editUserDisplayName').value=data.display_name||'';$('editUserRole').value=data.role||'member';$('editUserLanguage').value=data.preferred_language||'es';$('editUserDialog').dataset.active=data.active?'1':'0';text('editUserMsg','');$('editUserDialog').showModal();}
async function saveAdminEdit(e){e.preventDefault();e.stopImmediatePropagation();const email=$('editUserEmail').value;try{text('editUserMsg','Guardando…');await adminCall({action:'update',email,display_name:$('editUserDisplayName').value.trim(),role:$('editUserRole').value,preferred_language:$('editUserLanguage').value,active:$('editUserDialog').dataset.active!=='0'});$('editUserDialog').close();if(typeof renderAdminData==='function')await renderAdminData(false);}catch(err){text('editUserMsg',err.message);}}
async function toggleAdmin(email,newActive){try{await adminCall({action:'update',email,display_name:'',role:'member',preferred_language:'es',active:newActive});if(typeof renderAdminData==='function')await renderAdminData(false);}catch(err){alert(err.message);}}
async function deleteAdmin(email){if(!confirm('¿Eliminar este usuario y su acceso al curso?'))return;try{await adminCall({action:'delete',email});if(typeof renderAdminData==='function')await renderAdminData(false);}catch(err){alert(err.message);}}
function patchAdmin(){
 const save=$('saveEditedUserBtn');if(save&&!save.dataset.v195){save.dataset.v195='1';save.addEventListener('click',saveAdminEdit,true);}
 document.addEventListener('click',e=>{const a=e.target.closest('[data-admin-edit],[data-admin-toggle],[data-admin-delete]');if(!a)return;e.preventDefault();e.stopImmediatePropagation();if(a.dataset.adminEdit)return openAdminEdit(a.dataset.adminEdit);if(a.dataset.adminToggle)return toggleAdmin(a.dataset.adminToggle,a.dataset.active!=='1');if(a.dataset.adminDelete)return deleteAdmin(a.dataset.adminDelete);},true);
}

function syncRecoveryLanguageVisibility(){const box=$('recoveryBox'),top=document.querySelector('.login-language');if(!box||!top)return;top.classList.toggle('hidden',!box.classList.contains('hidden'));}
async function robustSetPassword(e){e.preventDefault();e.stopImmediatePropagation();const p1=$('newPassword').value,p2=$('newPassword2').value,lang=$('setupLanguage').value;if(!langs.includes(lang)){text('authMsg','Selecciona un idioma válido.');return;}if(p1.length<8){text('authMsg','La contraseña debe tener al menos 8 caracteres.');return;}if(p1!==p2){text('authMsg','Las contraseñas no coinciden.');return;}text('authMsg','Guardando configuración…');let s=await getSession();if(!s){await delay(500);s=await getSession();}if(!s){text('authMsg','El enlace de invitación todavía no ha creado una sesión válida. Abre de nuevo el último enlace recibido por correo.');return;}for(let i=0;i<2;i++){const {error}=await sb.auth.updateUser({password:p1,data:{...(s.user.user_metadata||{}),course_setup_complete:true,preferred_language:lang}});if(!error){const {error:pe}=await sb.rpc('update_my_course_profile',{p_display_name:accessProfile?.display_name||s.user.user_metadata?.display_name||'',p_preferred_language:lang});if(pe){text('authMsg',pe.message);return;}try{passwordRecoveryMode=false;currentLanguage=lang;pendingLoginLanguage=null;applyLanguage();}catch{}$('newPassword').value='';$('newPassword2').value='';if(typeof refreshAccess==='function')await refreshAccess();if(typeof syncOnLogin==='function')await syncOnLogin();if(typeof safeRenderAll==='function')safeRenderAll();text('authMsg','Acceso configurado correctamente.');return;}if(i===0)await delay(450);else text('authMsg',error.message);}}
function patchOnboarding(){const b=$('setNewPasswordBtn');if(b&&!b.dataset.v195){b.dataset.v195='1';b.addEventListener('click',robustSetPassword,true);}const rb=$('recoveryBox');if(rb){new MutationObserver(syncRecoveryLanguageVisibility).observe(rb,{attributes:true,attributeFilter:['class']});syncRecoveryLanguageVisibility();}}

const DIAG=[
 {q:'¿Cuál es la mejor forma de usar una respuesta de IA que contiene un dato importante para una decisión?',o:['Aceptar el dato si la explicación parece coherente.','Comprobar el dato en una fuente adecuada antes de decidir.','Pedir a la IA que confirme que está segura.','Reformular la misma pregunta hasta obtener la misma cifra.'],a:1,w:1},
 {q:'Quieres resumir un documento largo. ¿Qué instrucción mejora más la fiabilidad?',o:['“Resúmelo bien y sin errores”.','“Haz un resumen completo usando tu conocimiento general”.','“Resume solo el contenido del documento y separa hechos, dudas y datos no localizados”.','“Resume en diez puntos y completa lo que falte”.'],a:2,w:1},
 {q:'Una tarea se repite cada semana con entradas parecidas. ¿Qué enfoque suele aportar más valor?',o:['Escribir un prompt nuevo cada semana.','Diseñar una plantilla de instrucciones y un flujo repetible con revisión.','Pedir respuestas más largas para reducir omisiones.','Cambiar de modelo cada semana.'],a:1,w:1},
 {q:'¿Qué elemento aporta más control al delegar una tarea compleja?',o:['Indicar objetivo, contexto, restricciones, formato y criterio de comprobación.','Añadir muchos ejemplos aunque no sean relevantes.','Pedir siempre que la respuesta sea exhaustiva.','Evitar restricciones para que la IA tenga libertad.'],a:0,w:2},
 {q:'Si necesitas información que puede haber cambiado este mes, ¿qué es lo más adecuado?',o:['Usar la memoria del modelo si el tema es conocido.','Solicitar búsqueda actualizada y revisar las fuentes utilizadas.','Pedir una estimación y comprobarla solo si parece extraña.','Comparar dos respuestas del mismo modelo sin buscar fuentes.'],a:1,w:2},
 {q:'Al comparar tres ofertas en PDF, ¿qué flujo es más sólido?',o:['Pedir directamente cuál es la mejor.','Extraer criterios comparables, detectar faltantes y después analizar diferencias.','Resumir cada PDF por separado y elegir el resumen más convincente.','Convertir primero todos los PDF a texto y asumir que la extracción es completa.'],a:1,w:2},
 {q:'Una hoja de cálculo contiene importes y fórmulas. ¿Qué control es especialmente importante?',o:['Verificar totales, unidades, fórmulas y filas excluidas antes de usar conclusiones.','Confiar en la IA si identifica correctamente los encabezados.','Redondear todos los valores antes del análisis.','Ocultar las fórmulas para simplificar el archivo.'],a:0,w:3},
 {q:'¿Cuándo es razonable automatizar una tarea con poca supervisión?',o:['Cuando es frecuente, reversible, bien definida y el coste de error es bajo.','Cuando tarda mucho, aunque el error pueda tener consecuencias importantes.','Cuando la IA ya la realizó correctamente una vez.','Cuando no existe tiempo disponible para revisar.'],a:0,w:3},
 {q:'En un flujo con IA que termina en enviar una comunicación externa relevante, ¿qué diseño suele ser mejor?',o:['Que la IA redacte y envíe automáticamente para ahorrar tiempo.','Que la IA redacte, aplique comprobaciones y deje la aprobación final a una persona cuando el impacto lo justifique.','Que la persona redacte todo y la IA solo corrija ortografía.','Que dos modelos distintos voten y el ganador envíe el mensaje.'],a:1,w:4},
 {q:'¿Qué diferencia principal hay entre una respuesta aislada y un proceso fiable con IA?',o:['El proceso fiable usa prompts más largos.','El proceso define entradas, pasos, controles, excepciones, responsabilidad y salida esperada.','La respuesta aislada sirve solo para tareas personales.','El proceso fiable necesita siempre una aplicación programada.'],a:1,w:4}
];
function diagChapter(score){if(score>=21)return 7;if(score>=18)return 5;if(score>=14)return 4;if(score>=10)return 3;if(score>=6)return 2;return 1;}
function ensureDiagDialog(){if($('diagnosticDialog'))return;const d=document.createElement('dialog');d.id='diagnosticDialog';d.className='chapter-dialog diagnostic-dialog';d.innerHTML='<div class="dialog-body"><h2>Test inicial de nivel</h2><p>Son 10 preguntas breves. Sirven para evitar que tengas que completar contenidos que ya dominas.</p><div id="diagnosticQuestions"></div><div id="diagnosticMsg" class="muted"></div><div class="btnrow"><button id="diagnosticSubmit" class="btn primary" type="button">Evaluar nivel</button></div></div>';document.body.appendChild(d);$('diagnosticQuestions').innerHTML=DIAG.map((x,i)=>`<fieldset class="diagnostic-q"><legend>${i+1}. ${x.q}</legend>${x.o.map((v,j)=>`<label class="diagnostic-option"><input type="radio" name="dq${i}" value="${j}"><span>${v}</span></label>`).join('')}</fieldset>`).join('');$('diagnosticSubmit').onclick=submitDiagnostic;}
async function submitDiagnostic(){const s=await getSession();if(!s)return;const answers={};let score=0;for(let i=0;i<DIAG.length;i++){const c=document.querySelector(`input[name="dq${i}"]:checked`);if(!c){text('diagnosticMsg',`Falta responder la pregunta ${i+1}.`);return;}const v=Number(c.value);answers[i+1]=v;if(v===DIAG[i].a)score+=DIAG[i].w;}const chapter=diagChapter(score),max=DIAG.reduce((a,b)=>a+b.w,0);text('diagnosticMsg','Guardando resultado…');const {error}=await sb.from('course_diagnostic_results').upsert({user_id:s.user.id,score,max_score:max,recommended_chapter:chapter,answers,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()});if(error){text('diagnosticMsg',error.message);return;}const {data:pr}=await sb.from('course_progress_v2').select('data').eq('user_id',s.user.id).maybeSingle();const data=pr?.data&&typeof pr.data==='object'?pr.data:{};data.readingDone={...(data.readingDone||{})};data.practices={...(data.practices||{})};data.diagnosticSkipped={...(data.diagnosticSkipped||{})};for(let n=1;n<chapter;n++){data.readingDone[n]=true;data.practices[n]=true;data.diagnosticSkipped[n]=true;}data.updatedAt=new Date().toISOString();await sb.from('course_progress_v2').upsert({user_id:s.user.id,data,updated_at:new Date().toISOString()});try{state={...state,...data};saveLocal();if(typeof safeRenderAll==='function')safeRenderAll();}catch{}$('diagnosticDialog').close();alert(chapter===1?`Resultado: ${score}/${max}. Te recomendamos comenzar por el capítulo 1.`:`Resultado: ${score}/${max}. Puedes comenzar directamente por el capítulo ${chapter}; los anteriores quedan registrados como superados por diagnóstico.`);}
async function maybeDiagnostic(){try{const s=await getSession();if(!s||!accessProfile?.active||accessProfile?.role==='admin')return;const {data}=await sb.from('course_diagnostic_results').select('user_id').eq('user_id',s.user.id).maybeSingle();if(data)return;ensureDiagDialog();if(!$('recoveryBox')?.classList.contains('hidden'))return;if(!$('diagnosticDialog').open)$('diagnosticDialog').showModal();}catch{}}
function patchDiagnostic(){ensureDiagDialog();setInterval(maybeDiagnostic,1800);}

function version(){document.querySelectorAll('.shell-brand .pill').forEach(x=>x.textContent='v19.5');}
function init(){version();patchScrolling();patchNotes();patchProfile();patchAdmin();patchOnboarding();patchDiagnostic();setInterval(()=>{version();patchScrolling();patchProfile();patchOnboarding();},1200);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
