/* Curso IA ChatGPT v19.3 — módulo definitivo sobre v19.2 */
(()=>{
'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const types=['note','idea','prompt','test','application','task'];
const TXT={
 es:{notes:'Mis notas',desc:'Reúne las ideas, prompts, pruebas y aplicaciones que anotas mientras avanzas en el curso.',search:'Buscar en mis notas…',allCh:'Todos los capítulos',allTy:'Todos los tipos',new:'Nueva nota',chapter:'Capítulo',type:'Tipo',body:'Anotación',save:'Guardar nota',cancel:'Cancelar',edit:'Editar',copy:'Copiar',chat:'Trabajar con ChatGPT',del:'Eliminar',empty:'No hay notas que coincidan con el filtro.',saved:'Nota guardada.',updated:'Nota actualizada.',deleted:'Nota eliminada.',copied:'Copiado al portapapeles.',chatCopied:'He copiado un prompt preparado. Pégalo en ChatGPT para continuar.',note:'Nota',idea:'Idea',prompt:'Prompt',test:'Prueba',application:'Aplicación',task:'Tarea pendiente',add:'Añadir nota',openChapter:'Ir al capítulo',back:'← Volver'},
 en:{notes:'My notes',desc:'Collect ideas, prompts, tests and applications while you progress through the course.',search:'Search my notes…',allCh:'All chapters',allTy:'All types',new:'New note',chapter:'Chapter',type:'Type',body:'Note',save:'Save note',cancel:'Cancel',edit:'Edit',copy:'Copy',chat:'Work with ChatGPT',del:'Delete',empty:'No notes match this filter.',saved:'Note saved.',updated:'Note updated.',deleted:'Note deleted.',copied:'Copied to clipboard.',chatCopied:'A prepared prompt was copied. Paste it into ChatGPT to continue.',note:'Note',idea:'Idea',prompt:'Prompt',test:'Test',application:'Application',task:'Pending task',add:'Add note',openChapter:'Open chapter',back:'← Back'},
 fr:{notes:'Mes notes',desc:'Regroupez les idées, prompts, essais et applications notés pendant le cours.',search:'Rechercher dans mes notes…',allCh:'Tous les chapitres',allTy:'Tous les types',new:'Nouvelle note',chapter:'Chapitre',type:'Type',body:'Note',save:'Enregistrer',cancel:'Annuler',edit:'Modifier',copy:'Copier',chat:'Travailler avec ChatGPT',del:'Supprimer',empty:'Aucune note ne correspond au filtre.',saved:'Note enregistrée.',updated:'Note mise à jour.',deleted:'Note supprimée.',copied:'Copié.',chatCopied:'Un prompt préparé a été copié. Collez-le dans ChatGPT.',note:'Note',idea:'Idée',prompt:'Prompt',test:'Essai',application:'Application',task:'Tâche',add:'Ajouter une note',openChapter:'Ouvrir le chapitre',back:'← Retour'},
 de:{notes:'Meine Notizen',desc:'Ideen, Prompts, Tests und Anwendungen aus dem Kurs gesammelt anzeigen.',search:'Notizen durchsuchen…',allCh:'Alle Kapitel',allTy:'Alle Typen',new:'Neue Notiz',chapter:'Kapitel',type:'Typ',body:'Notiz',save:'Speichern',cancel:'Abbrechen',edit:'Bearbeiten',copy:'Kopieren',chat:'Mit ChatGPT bearbeiten',del:'Löschen',empty:'Keine Notizen für diesen Filter.',saved:'Notiz gespeichert.',updated:'Notiz aktualisiert.',deleted:'Notiz gelöscht.',copied:'Kopiert.',chatCopied:'Ein vorbereiteter Prompt wurde kopiert. Fügen Sie ihn in ChatGPT ein.',note:'Notiz',idea:'Idee',prompt:'Prompt',test:'Test',application:'Anwendung',task:'Aufgabe',add:'Notiz hinzufügen',openChapter:'Kapitel öffnen',back:'← Zurück'},
 it:{notes:'Le mie note',desc:'Raccogli idee, prompt, prove e applicazioni annotate durante il corso.',search:'Cerca nelle note…',allCh:'Tutti i capitoli',allTy:'Tutti i tipi',new:'Nuova nota',chapter:'Capitolo',type:'Tipo',body:'Nota',save:'Salva',cancel:'Annulla',edit:'Modifica',copy:'Copia',chat:'Lavora con ChatGPT',del:'Elimina',empty:'Nessuna nota corrisponde al filtro.',saved:'Nota salvata.',updated:'Nota aggiornata.',deleted:'Nota eliminata.',copied:'Copiato.',chatCopied:'È stato copiato un prompt preparato. Incollalo in ChatGPT.',note:'Nota',idea:'Idea',prompt:'Prompt',test:'Prova',application:'Applicazione',task:'Attività',add:'Aggiungi nota',openChapter:'Vai al capitolo',back:'← Indietro'},
 pt:{notes:'As minhas notas',desc:'Reúna ideias, prompts, testes e aplicações anotados ao longo do curso.',search:'Pesquisar nas notas…',allCh:'Todos os capítulos',allTy:'Todos os tipos',new:'Nova nota',chapter:'Capítulo',type:'Tipo',body:'Nota',save:'Guardar',cancel:'Cancelar',edit:'Editar',copy:'Copiar',chat:'Trabalhar com ChatGPT',del:'Eliminar',empty:'Nenhuma nota corresponde ao filtro.',saved:'Nota guardada.',updated:'Nota atualizada.',deleted:'Nota eliminada.',copied:'Copiado.',chatCopied:'Foi copiado um prompt preparado. Cole-o no ChatGPT.',note:'Nota',idea:'Ideia',prompt:'Prompt',test:'Teste',application:'Aplicação',task:'Tarefa',add:'Adicionar nota',openChapter:'Ir para o capítulo',back:'← Voltar'}
};
const T=()=>TXT[(typeof currentLanguage!=='undefined'&&TXT[currentLanguage])?currentLanguage:'es'];
let notesCache=[],editing=null,saveTimer=null;
function title(n){try{return courseContent?.[n]?.title||metadata(n)?.[0]||`Capítulo ${n}`;}catch(e){return `Capítulo ${n}`;}}
function version(){document.querySelectorAll('.shell-brand .pill').forEach(x=>{if(x.textContent!=='v19.3')x.textContent='v19.3';});}
function langRefresh(){const card=$('openNotesZoneBtn');if(card){card.querySelector('strong').textContent=T().notes;card.querySelector('span:last-child').textContent=T().desc;}if($('notesWorkspaceTitle'))$('notesWorkspaceTitle').textContent=T().notes;if($('closeNotesZoneBtn'))$('closeNotesZoneBtn').textContent=T().back;if($('profileNotesBtn'))$('profileNotesBtn').textContent=`✎ ${T().notes}`;fillSelects();}
function addHome(){const g=document.querySelector('#homeMenu .zone-grid');if(!g||$('openNotesZoneBtn'))return;const b=document.createElement('button');b.id='openNotesZoneBtn';b.className='zone-card';b.type='button';b.innerHTML=`<div class="zone-icon">✎</div><strong>${esc(T().notes)}</strong><span>${esc(T().desc)}</span>`;b.addEventListener('click',openNotes);g.appendChild(b);}
function addWorkspace(){if($('misNotas'))return;const shell=$('appShell');if(!shell)return;const s=document.createElement('section');s.id='misNotas';s.className='workspace';s.innerHTML=`<div class="workspace-head"><div class="workspace-head-inner"><button id="closeNotesZoneBtn" class="icon-btn" type="button">${esc(T().back)}</button><div id="notesWorkspaceTitle" class="workspace-title">${esc(T().notes)}</div></div></div><div class="notes-workspace-body"><div class="card"><h2>${esc(T().notes)}</h2><p id="notesHubDesc">${esc(T().desc)}</p><div class="notes-toolbar"><input id="notesSearch" type="search" placeholder="${esc(T().search)}"><select id="notesChapterFilter"></select><select id="notesTypeFilter"></select></div></div><div id="noteEditorCard" class="card hidden"><h3 id="noteEditorTitle"></h3><div class="note-editor"><div class="note-editor-grid"><div><label id="noteChapterLabel" for="noteEditorChapter"></label><select id="noteEditorChapter"></select></div><div><label id="noteTypeLabel" for="noteEditorType"></label><select id="noteEditorType"></select></div></div><div><label id="noteBodyLabel" for="noteEditorBody"></label><textarea id="noteEditorBody" rows="6"></textarea></div><div class="btnrow"><button id="saveNoteBtn" class="btn primary" type="button"></button><button id="cancelNoteBtn" class="btn" type="button"></button></div></div></div><div class="btnrow"><button id="newNoteBtn" class="btn primary" type="button"></button></div><div id="notesStatus" class="notes-status"></div><div id="notesList" class="notes-list"></div></div>`;shell.appendChild(s);$('closeNotesZoneBtn').addEventListener('click',closeNotes);$('newNoteBtn').addEventListener('click',()=>editor());$('cancelNoteBtn').addEventListener('click',closeEditor);$('saveNoteBtn').addEventListener('click',saveNote);$('notesSearch').addEventListener('input',renderNotes);$('notesChapterFilter').addEventListener('change',renderNotes);$('notesTypeFilter').addEventListener('change',renderNotes);fillSelects();}
function fillSelects(){if(!$('notesChapterFilter'))return;const t=T(),ch=Array.from({length:17},(_,i)=>`<option value="${i+1}">${i+1}. ${esc(title(i+1))}</option>`).join(''),ty=types.map(x=>`<option value="${x}">${esc(t[x]||x)}</option>`).join('');$('notesChapterFilter').innerHTML=`<option value="">${esc(t.allCh)}</option>${ch}`;$('noteEditorChapter').innerHTML=`<option value="">—</option>${ch}`;$('notesTypeFilter').innerHTML=`<option value="">${esc(t.allTy)}</option>${ty}`;$('noteEditorType').innerHTML=ty;$('notesSearch').placeholder=t.search;$('notesHubDesc').textContent=t.desc;$('noteChapterLabel').textContent=t.chapter;$('noteTypeLabel').textContent=t.type;$('noteBodyLabel').textContent=t.body;$('saveNoteBtn').textContent=t.save;$('cancelNoteBtn').textContent=t.cancel;$('newNoteBtn').textContent=`＋ ${t.add}`;}
function addProfile(){const c=$('profileCard');if(!c)return;const pr=$('profileProgressValue')?.closest('.profile-row');if(pr)pr.classList.add('v19-hide-progress');if($('profileNotesBtn'))return;const d=document.createElement('div');d.className='profile-notes-shortcut';d.innerHTML=`<button id="profileNotesBtn" class="btn" type="button">✎ ${esc(T().notes)}</button>`;c.appendChild(d);$('profileNotesBtn').addEventListener('click',openNotes);}
function openNotes(){if(typeof session==='undefined'||!session||typeof accessProfile==='undefined'||!accessProfile?.active)return;document.querySelectorAll('.workspace').forEach(w=>w.classList.remove('open'));$('misNotas').classList.add('open');document.body.style.overflow='hidden';langRefresh();loadNotes();}
function closeNotes(){$('misNotas')?.classList.remove('open');document.body.style.overflow='';$('homeMenu')?.scrollIntoView({block:'start'});}
async function loadNotes(){if(typeof sb==='undefined'||!sb||typeof session==='undefined'||!session)return;$('notesStatus').textContent='…';const {data,error}=await sb.from('course_notes').select('id,chapter_number,note_type,body,source_label,created_at,updated_at').order('updated_at',{ascending:false});if(error){$('notesStatus').textContent=error.message;return;}notesCache=data||[];$('notesStatus').textContent='';renderNotes();}
function fmt(v){try{return new Intl.DateTimeFormat(currentLanguage==='en'?'en-GB':currentLanguage,{dateStyle:'short',timeStyle:'short'}).format(new Date(v));}catch(e){return '';}}
function renderNotes(){const b=$('notesList');if(!b)return;const q=String($('notesSearch').value||'').trim().toLocaleLowerCase(),ch=$('notesChapterFilter').value,ty=$('notesTypeFilter').value,t=T(),rows=notesCache.filter(n=>(!ch||String(n.chapter_number||'')===ch)&&(!ty||n.note_type===ty)&&(!q||String(n.body).toLocaleLowerCase().includes(q)));if(!rows.length){b.innerHTML=`<div class="notes-empty">${esc(t.empty)}</div>`;return;}b.innerHTML=rows.map(n=>`<article class="note-item"><div class="note-item-head"><div class="note-meta">${n.chapter_number?`<span class="note-chip">${esc(t.chapter)} ${n.chapter_number}</span>`:''}<span class="note-chip">${esc(t[n.note_type]||n.note_type)}</span></div><span class="muted">${fmt(n.updated_at)}</span></div><div class="note-body">${esc(n.body)}</div><div class="note-actions">${n.chapter_number?`<button class="btn" data-open-ch="${n.chapter_number}" type="button">${esc(t.openChapter)}</button>`:''}<button class="btn" data-edit="${n.id}" type="button">${esc(t.edit)}</button><button class="btn" data-copy="${n.id}" type="button">${esc(t.copy)}</button><button class="btn primary" data-chat="${n.id}" type="button">${esc(t.chat)}</button><button class="btn danger-soft" data-del="${n.id}" type="button">${esc(t.del)}</button></div></article>`).join('');b.querySelectorAll('[data-open-ch]').forEach(x=>x.addEventListener('click',()=>goChapter(Number(x.dataset.openCh))));b.querySelectorAll('[data-edit]').forEach(x=>x.addEventListener('click',()=>editor(notesCache.find(n=>n.id===x.dataset.edit))));b.querySelectorAll('[data-copy]').forEach(x=>x.addEventListener('click',()=>copy(notesCache.find(n=>n.id===x.dataset.copy)?.body||'',t.copied)));b.querySelectorAll('[data-chat]').forEach(x=>x.addEventListener('click',()=>chat(notesCache.find(n=>n.id===x.dataset.chat))));b.querySelectorAll('[data-del]').forEach(x=>x.addEventListener('click',()=>delNote(x.dataset.del)));}
function goChapter(n){closeNotes();try{current=n;opts();safeRenderAll();document.querySelectorAll('.workspace').forEach(w=>w.classList.toggle('open',w.id==='curso'));document.body.style.overflow='hidden';$('curso').scrollTop=0;}catch(e){}}
function editor(n=null){editing=n||null;$('noteEditorCard').classList.remove('hidden');$('noteEditorTitle').textContent=n?T().edit:T().new;$('noteEditorChapter').value=n?.chapter_number?String(n.chapter_number):String((typeof current!=='undefined'&&current>0)?current:'');$('noteEditorType').value=n?.note_type||'note';$('noteEditorBody').value=n?.body||'';$('noteEditorBody').focus();}
function closeEditor(){editing=null;$('noteEditorCard').classList.add('hidden');$('noteEditorBody').value='';}
async function saveNote(){if(!sb||!session)return;const body=$('noteEditorBody').value.trim();if(!body)return;const payload={user_id:session.user.id,chapter_number:$('noteEditorChapter').value?Number($('noteEditorChapter').value):null,note_type:$('noteEditorType').value,body,source_label:editing?.source_label||'notes-hub'};let error;if(editing)({error}=await sb.from('course_notes').update(payload).eq('id',editing.id));else({error}=await sb.from('course_notes').insert(payload));if(error){$('notesStatus').textContent=error.message;return;}if(editing?.source_label==='chapter-theory-live'&&editing.chapter_number){state.notes[editing.chapter_number]=body;saveLocal();}const was=!!editing;closeEditor();$('notesStatus').textContent=was?T().updated:T().saved;await loadNotes();}
async function delNote(id){const n=notesCache.find(x=>x.id===id);if(!n||!confirm(`${T().del}?`))return;const {error}=await sb.from('course_notes').delete().eq('id',id);if(error){$('notesStatus').textContent=error.message;return;}if(n.source_label==='chapter-theory-live'&&n.chapter_number){state.notes[n.chapter_number]='';saveLocal();} $('notesStatus').textContent=T().deleted;await loadNotes();}
async function copy(text,msg){try{await navigator.clipboard.writeText(text);}catch(e){const a=document.createElement('textarea');a.value=text;document.body.appendChild(a);a.select();document.execCommand('copy');a.remove();}$('notesStatus').textContent=msg||T().copied;}
function chat(n){if(!n)return;const ctx=n.chapter_number?`${T().chapter} ${n.chapter_number}: ${title(n.chapter_number)}`:'Curso IA';const p=`Quiero trabajar esta anotación surgida mientras realizaba el Curso IA.\n\nContexto: ${ctx}\nTipo: ${T()[n.note_type]||n.note_type}\n\nAnotación:\n${n.body}\n\nAyúdame a convertirla en algo práctico. Primero interpreta qué quiero conseguir. Después propón un enfoque concreto y, cuando tenga sentido, un prompt reutilizable, una prueba o un flujo de trabajo. Indica también qué debería verificar antes de utilizar el resultado.`;window.open('https://chatgpt.com/','_blank','noopener,noreferrer');copy(p,T().chatCopied);}
function scrollTopButton(){if($('theoryScrollTopBtn'))return;const ws=$('curso');if(!ws)return;const b=document.createElement('button');b.id='theoryScrollTopBtn';b.type='button';b.textContent='↑';b.title='Volver arriba';b.setAttribute('aria-label','Volver arriba');document.body.appendChild(b);const show=()=>b.classList.toggle('visible',ws.classList.contains('open')&&ws.scrollTop>320);ws.addEventListener('scroll',show,{passive:true});b.addEventListener('click',()=>ws.scrollTo({top:0,behavior:'smooth'}));}
async function mirrorTheoryNote(){if(!sb||!session||typeof current==='undefined'||current<1||!$('notes'))return;const ch=Number(current),body=$('notes').value.trim();const {data,error}=await sb.from('course_notes').select('id,body').eq('chapter_number',ch).eq('source_label','chapter-theory-live').maybeSingle();if(error)return;if(!body){if(data?.id)await sb.from('course_notes').delete().eq('id',data.id);return;}if(data?.id){if(data.body!==body)await sb.from('course_notes').update({body,note_type:'note'}).eq('id',data.id);}else await sb.from('course_notes').insert({user_id:session.user.id,chapter_number:ch,note_type:'note',body,source_label:'chapter-theory-live'});}
function hookTheoryNotes(){const a=$('notes');if(!a||a.dataset.v193)return;a.dataset.v193='1';a.addEventListener('input',()=>{clearTimeout(saveTimer);saveTimer=setTimeout(mirrorTheoryNote,900);});a.addEventListener('blur',()=>{clearTimeout(saveTimer);mirrorTheoryNote();});}
function languageHooks(){['loginLanguageSelect','setupLanguage','profileEditLanguage'].forEach(id=>$(id)?.addEventListener('change',()=>setTimeout(langRefresh,0)));}
function init(){version();addHome();addWorkspace();addProfile();scrollTopButton();hookTheoryNotes();languageHooks();langRefresh();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
